"""add_field_to_items

Revision ID: 9cc660270c3d
Revises: 4a149ba61080
Create Date: 2025-11-19 22:45:45.939474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9cc660270c3d'
down_revision: Union[str, Sequence[str], None] = '4a149ba61080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dup_group_meta_dup_group_id'), table_name='dup_group_meta')
    op.drop_index(op.f('ix_dup_group_meta_first_seen_at'), table_name='dup_group_meta')
    op.drop_index(op.f('ix_dup_group_meta_last_updated_at'), table_name='dup_group_meta')
    op.drop_table('dup_group_meta')
    op.add_column('items', sa.Column('field', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_items_field'), 'items', ['field'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_field'), table_name='items')
    op.drop_column('items', 'field')
    op.create_table('dup_group_meta',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dup_group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('first_seen_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('member_count', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('dup_group_meta_pkey'))
    )
    op.create_index(op.f('ix_dup_group_meta_last_updated_at'), 'dup_group_meta', ['last_updated_at'], unique=False)
    op.create_index(op.f('ix_dup_group_meta_first_seen_at'), 'dup_group_meta', ['first_seen_at'], unique=False)
    op.create_index(op.f('ix_dup_group_meta_dup_group_id'), 'dup_group_meta', ['dup_group_id'], unique=True)
    # ### end Alembic commands ###
