"""add_field_to_items

Revision ID: 9cc660270c3d
Revises: 4a149ba61080
Create Date: 2025-11-19 22:45:45.939474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9cc660270c3d'
down_revision: Union[str, Sequence[str], None] = '4a149ba61080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add field column, do not drop dup_group_meta table
    op.add_column('items', sa.Column('field', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_items_field'), 'items', ['field'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_field'), table_name='items')
    op.drop_column('items', 'field')
    # ### end Alembic commands ###
