"""Initial migration

Revision ID: ea1fbe012a50
Revises: 
Create Date: 2025-11-15 12:32:45.581693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea1fbe012a50'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('PERSON', 'ORGANIZATION', 'TECHNOLOGY', name='entitytype'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_id'), 'entities', ['id'], unique=False)
    op.create_index(op.f('ix_entities_name'), 'entities', ['name'], unique=True)
    op.create_index(op.f('ix_entities_type'), 'entities', ['type'], unique=False)
    op.create_table('persons',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persons_id'), 'persons', ['id'], unique=False)
    op.create_index(op.f('ix_persons_name'), 'persons', ['name'], unique=True)
    op.create_table('sources',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('feed_url', sa.String(length=512), nullable=False),
    sa.Column('site_url', sa.String(length=512), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('lang', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_feed_url'), 'sources', ['feed_url'], unique=True)
    op.create_index(op.f('ix_sources_id'), 'sources', ['id'], unique=False)
    op.create_table('items',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('summary_short', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=1024), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=1024), nullable=True),
    sa.Column('iptc_topics', sa.JSON(), nullable=False),
    sa.Column('iab_categories', sa.JSON(), nullable=False),
    sa.Column('custom_tags', sa.JSON(), nullable=False),
    sa.Column('dup_group_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_dup_group_id'), 'items', ['dup_group_id'], unique=False)
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_link'), 'items', ['link'], unique=True)
    op.create_index(op.f('ix_items_published_at'), 'items', ['published_at'], unique=False)
    op.create_index(op.f('ix_items_source_id'), 'items', ['source_id'], unique=False)
    op.create_index(op.f('ix_items_title'), 'items', ['title'], unique=False)
    op.create_table('watch_rules',
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('include_rules', sa.JSON(), nullable=False),
    sa.Column('exclude_rules', sa.JSON(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watch_rules_id'), 'watch_rules', ['id'], unique=False)
    op.create_table('bookmarks',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookmarks_id'), 'bookmarks', ['id'], unique=False)
    op.create_index(op.f('ix_bookmarks_item_id'), 'bookmarks', ['item_id'], unique=False)
    op.create_table('item_entities',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'entity_id')
    )
    op.create_table('person_timeline',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_timeline_id'), 'person_timeline', ['id'], unique=False)
    op.create_index(op.f('ix_person_timeline_item_id'), 'person_timeline', ['item_id'], unique=False)
    op.create_index(op.f('ix_person_timeline_person_id'), 'person_timeline', ['person_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_person_timeline_person_id'), table_name='person_timeline')
    op.drop_index(op.f('ix_person_timeline_item_id'), table_name='person_timeline')
    op.drop_index(op.f('ix_person_timeline_id'), table_name='person_timeline')
    op.drop_table('person_timeline')
    op.drop_table('item_entities')
    op.drop_index(op.f('ix_bookmarks_item_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_id'), table_name='bookmarks')
    op.drop_table('bookmarks')
    op.drop_index(op.f('ix_watch_rules_id'), table_name='watch_rules')
    op.drop_table('watch_rules')
    op.drop_index(op.f('ix_items_title'), table_name='items')
    op.drop_index(op.f('ix_items_source_id'), table_name='items')
    op.drop_index(op.f('ix_items_published_at'), table_name='items')
    op.drop_index(op.f('ix_items_link'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_index(op.f('ix_items_dup_group_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_sources_id'), table_name='sources')
    op.drop_index(op.f('ix_sources_feed_url'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_persons_name'), table_name='persons')
    op.drop_index(op.f('ix_persons_id'), table_name='persons')
    op.drop_table('persons')
    op.drop_index(op.f('ix_entities_type'), table_name='entities')
    op.drop_index(op.f('ix_entities_name'), table_name='entities')
    op.drop_index(op.f('ix_entities_id'), table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
